// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjWFgcO6gWOjmk5vqUjxDTcFpGFj_hOd8',
    appId: '1:216678536759:web:0ac2284f1b0657b32b91b2',
    messagingSenderId: '216678536759',
    projectId: 'excellencecoachinghub-5597c',
    authDomain: 'excellencecoachinghub-5597c.firebaseapp.com',
    storageBucket: 'excellencecoachinghub-5597c.firebasestorage.app',
    measurementId: 'G-DG75MXWVX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrDh_HTXexEbp98YOsTb5Y_NRcxufj-iI',
    appId: '1:216678536759:android:f024947f5605bbbc2b91b2',
    messagingSenderId: '216678536759',
    projectId: 'excellencecoachinghub-5597c',
    storageBucket: 'excellencecoachinghub-5597c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiUtqtDfiJ4P5-QW46VdV3vbi3PHfUM-Q',
    appId: '1:216678536759:ios:d853269f6aeefc052b91b2',
    messagingSenderId: '216678536759',
    projectId: 'excellencecoachinghub-5597c',
    storageBucket: 'excellencecoachinghub-5597c.firebasestorage.app',
    iosBundleId: 'com.example.excellenceCoachingHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiUtqtDfiJ4P5-QW46VdV3vbi3PHfUM-Q',
    appId: '1:216678536759:ios:d853269f6aeefc052b91b2',
    messagingSenderId: '216678536759',
    projectId: 'excellencecoachinghub-5597c',
    storageBucket: 'excellencecoachinghub-5597c.firebasestorage.app',
    iosBundleId: 'com.example.excellenceCoachingHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjWFgcO6gWOjmk5vqUjxDTcFpGFj_hOd8',
    appId: '1:216678536759:web:82fbe3530b404ff02b91b2',
    messagingSenderId: '216678536759',
    projectId: 'excellencecoachinghub-5597c',
    authDomain: 'excellencecoachinghub-5597c.firebaseapp.com',
    storageBucket: 'excellencecoachinghub-5597c.firebasestorage.app',
    measurementId: 'G-9L37F42P10',
  );
}
